config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index", as: :root
  resources :tournaments, only: %i[index show]
  get "/ranking", to: "ranking#index", as: "ranking"
  get "/search", to: "search#index", as: "search"

  resources :athletes, only: %i[index show] do
    member do
      get "graph"
    end
  end

  namespace :admin do
    root to: "home#index", as: :root
    get "login", to: "sessions#new", as: :new_session
    post "login", to: "sessions#create", as: :session
    delete "logout", to: "sessions#destroy", as: :destroy_session

    resources :competitions
    resources :athletes
    resources :tournaments
    resources :short_results
    resources :long_results
    resources :field_results
    resources :relay_results
    resources :road_results
    resources :decathlon_results
    resources :ekidens do
      resources :raps do
        post :broadcast, to: "raps#broadcast"
      end
      resources :kukans
      resources :points
    end
  end

  get "/mentenance", to: "mentenance#index", as: "mentenance"
  root "errors#routing_error"
  get "*anything" => "errors#routing_error"
end

app/views/layouts/admin/application.html.slim
doctype html
html
  head
    title
      | リザルトシステム -管理画面
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .ui.inverted.left.vertical.visible.blue.sidebar.menu
      = link_to admin_root_path, class: 'item' do
        h3 リザルトシステム管理画面
      .item.ui.inverted
        .ui.inverted.accordion
          .title.active
            h5
              i.dropdown.icon
              | 結果管理
          .content.active
            .item.inverted
              .inverted.accordion
                .title.active
                  h5
                    i.dropdown.icon
                    | 短距離種目(〜400m)
                .content.active
                  = link_to new_admin_short_result_path, class: 'item' do
                    | 新規作成
                  = link_to admin_short_results_path, class: 'item' do
                    | 一覧
            .item.inverted
              .inverted.accordion
                .title.active
                  h5
                    i.dropdown.icon
                    | 中長距離種目(800m〜)
                .content.active
                  = link_to new_admin_long_result_path, class: 'item' do
                    | 新規作成
                  = link_to admin_long_results_path, class: 'item' do
                    | 一覧
            .item.inverted
              .inverted.accordion
                .title.active
                  h5
                    i.dropdown.icon
                    | フィールド種目
                .content.active
                  = link_to new_admin_field_result_path, class: 'item' do
                    | 新規作成
                  = link_to admin_field_results_path, class: 'item' do
                    | 一覧
            .item.inverted
              .inverted.accordion
                .title.active
                  h5
                    i.dropdown.icon
                    | リレー種目
                .content.active
                  = link_to new_admin_relay_result_path, class: 'item' do
                    | 新規作成
                  = link_to admin_relay_results_path, class: 'item' do
                    | 一覧
            .item.inverted
            .item.inverted
              .inverted.accordion
                .title.active
                  h5
                    i.dropdown.icon
                    | 十種競技
                .content
                  = link_to nil, class: 'item' do
                    | 新規作成
                  = link_to nil, class: 'item' do
                    | 一覧
      .item.ui.inverted
        .ui.inverted
          .content
            = link_to admin_tournaments_path, class: 'item' do
              | 大会管理
      .item.ui.inverted
        .ui.inverted
          .content
            = link_to admin_athletes_path, class: 'item' do
              | 選手管理
      .item.ui.inverted
        .ui.inverted.accordion
          .title.active
            h5
              i.dropdown.icon
              | 一年間の結果
          .content
            = link_to nil, class: 'item' do
              | 2018年
            = link_to nil, class: 'item' do
              | 2017年
            = link_to nil, class: 'item' do
              | 2016年
            = link_to nil, class: 'item' do
              | 2015年
      
      = link_to admin_destroy_session_path, method: :delete, class: 'item ui inverted' do
        .title
          i.sign.out.icon
          | ログアウト

    .pusher
      .ui.admin.container
        == yield

app/views/layouts/admin/base.html.slim
doctype html
html
  head
    title
      | リザルト -管理画面
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag('icon.jpg')
    meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"
  body
    - unless @smartphone
      .ui.top.labeled.inverted.huge.menu
        .menu
          = link_to 'HOME', admin_root_path, class: 'ui item'
          .ui.dropdown.item
            i.flag.icon
            | 大会
            i.dropdown.icon
            .menu
              = link_to '一覧', admin_tournaments_path, class: 'ui item'
              = link_to '新規作成', new_admin_tournament_path, class: 'ui item'
        .ui.dropdown.item
          | 短距離
          i.dropdown.icon
          .menu
            = link_to '一覧', admin_short_results_path, class: 'ui item'
            = link_to '新規作成', new_admin_short_result_path, class: 'ui item'
        .ui.dropdown.item
          | 長距離
          i.dropdown.icon
          .menu
            = link_to '一覧', admin_long_results_path, class: 'ui item'
            = link_to '新規作成', new_admin_long_result_path, class: 'ui item'
        .ui.dropdown.item
          | フィールド
          i.dropdown.icon
          .menu
            = link_to '一覧', admin_field_results_path, class: 'ui item'
            = link_to '新規作成', new_admin_field_result_path, class: 'ui item'
        .ui.dropdown.item
          | ロード種目
          i.dropdown.icon
          .menu
            = link_to '一覧', admin_road_results_path, class: 'ui item'
            = link_to '新規作成', new_admin_road_result_path, class: 'ui item'
        .ui.dropdown.item
          | リレー
          i.dropdown.icon
          .menu
            = link_to '一覧', admin_relay_results_path, class: 'ui item'
            = link_to '新規作成', new_admin_relay_result_path, class: 'ui item'
        .ui.dropdown.item
          | 十種
          i.dropdown.icon
          .menu
            = link_to '一覧', admin_decathlon_results_path, class: 'ui item'
            = link_to '新規作成', new_admin_decathlon_result_path, class: 'ui item'
        .ui.dropdown.item
          i.user.icon
          | 選手
          i.dropdown.icon
          .menu
            = link_to '一覧', admin_athletes_path, class: 'ui item'
            = link_to '新規作成', new_admin_athlete_path, class: 'ui item'
        = link_to admin_destroy_session_path, method: :delete, class: 'ui right item' do
          i.sign.out.icon
          | ログアウト

      .ui.stackable.admin.container
        - if flash.present?
          .ui.positive.message
            - flash.each do |key, value|
              = content_tag(:div, value, class: "#{key}")
        == yield

    - if @smartphone
      .ui.stackable.labeled.inverted.large.left.vertical.nocp.sidebar.menu
        = link_to 'HOME', admin_root_path, class: 'ui item'
        .ui.item
          .ui.inverted.accordion
            .title
              | 大会
              i.dropdown.icon
            .content
              = link_to '一覧', admin_tournaments_path, class: 'ui inverted item'
              = link_to '新規作成', new_admin_tournament_path, class: 'ui item'
        .ui.item
          .ui.inverted.accordion
            .title
              | 短距離
              i.dropdown.icon
            .content
              = link_to '一覧', admin_short_results_path, class: 'ui item'
              = link_to '新規作成', new_admin_short_result_path, class: 'ui item'
        .ui.item
          .ui.inverted.accordion
            .title
              | 長距離
              i.dropdown.icon
            .content
              = link_to '一覧', admin_long_results_path, class: 'ui item'
              = link_to '新規作成', new_admin_long_result_path, class: 'ui item'
        .ui.item
          .ui.inverted.accordion
            .title
              | フィールド
              i.dropdown.icon
            .content
              = link_to '一覧', admin_field_results_path, class: 'ui item'
              = link_to '新規作成', new_admin_field_result_path, class: 'ui item'
        .ui.item
          .ui.inverted.accordion
            .title
              | リレー
              i.dropdown.icon
            .content
              = link_to '一覧', admin_relay_results_path, class: 'ui item'
              = link_to '新規作成', new_admin_relay_result_path, class: 'ui item'
        .ui.item
          .ui.inverted.accordion
            .title
              | 十種
              i.dropdown.icon
            .content
              = link_to '一覧', admin_decathlon_results_path, class: 'ui item'
              = link_to '新規作成', new_admin_decathlon_result_path, class: 'ui item'
        .ui.item
          .ui.inverted.accordion
            .title
              | 選手
              i.dropdown.icon
            .content
              = link_to '一覧', admin_athletes_path, class: 'ui item'
              = link_to '新規作成', new_admin_athlete_path, class: 'ui item'
        = link_to admin_destroy_session_path, method: :delete, class: 'ui right item' do
          i.sign.out.icon
          | ログアウト

      .pusher style="padding-left: 50px"
        .ui.sidebar.inverted.visible.sidebar.main.menu
          a.launch.icon.item id="sidebar"
            i.sidebar.icon
        .content
          .ui.stackable.admin.container
            - if flash.present?
              .ui.positive.message
                - flash.each do |key, value|
                  = content_tag(:div, value, class: "#{key}")
            == yield