config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index", as: :root
  resources :tournaments, only: %i[index show]
  get "/ranking", to: "ranking#index", as: "ranking"
  get "/search", to: "search#index", as: "search"

  resources :athletes, only: %i[index show] do
    member do
      get "graph"
    end
  end

  namespace :admin do
    root to: "home#index", as: :root
    get "login", to: "sessions#new", as: :new_session
    post "login", to: "sessions#create", as: :session
    delete "logout", to: "sessions#destroy", as: :destroy_session

    resources :competitions
    resources :athletes
    resources :tournaments
    resources :short_results
    resources :long_results
    resources :field_results
    resources :relay_results
    resources :road_results
    resources :decathlon_results
    resources :ekidens do
      resources :raps do
        post :broadcast, to: "raps#broadcast"
      end
      resources :kukans
      resources :points
    end
  end

  get "/mentenance", to: "mentenance#index", as: "mentenance"
  root "errors#routing_error"
  get "*anything" => "errors#routing_error"
end

app/models/point.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: points
#
#  id        :bigint           not null, primary key
#  name      :string
#  ekiden_id :integer
#
class Point < ApplicationRecord
  belongs_to :ekiden
end

app/controllers/admin/points_controller.rb
# frozen_string_literal: true

class Admin::PointsController < Admin::BaseController
  before_action :set_ekiden
  before_action :set_point, only: %i[edit update destroy]

  def index
    @points = Point.where(ekiden_id: @ekiden.id)
  end

  def new
    @point = Point.new
  end

  def edit
  end

  def create
    @point = Point.new(point_params.merge(ekiden_id: @ekiden.id))
    if @point.save
      flash[:notice] = "新規作成しました"
      redirect_to admin_ekiden_points_path(@ekiden)
    else
      flash[:notice] = "新規作成に失敗しました"
      render :new
    end
  end

  def update
    if @point.update(point_params)
      flash[:notice] = "更新しました"
      redirect_to admin_ekiden_points_path(@ekiden)
    else
      flash[:notice] = "更新に失敗しました"
      render :edit
    end
  end

  def destroy
    flash[:notice] = if @point.destroy
                       "削除しました"
                     else
                       "削除に失敗しました"
                     end
    redirect_to admin_ekiden_points_path(@ekiden)
  end

  private

    def set_ekiden
      @ekiden = Ekiden.find(params[:ekiden_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_point
      @point = Point.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def point_params
      params.require(:point).permit(:name)
    end
end

app/views/admin/points/_form.html.slim
- if @point.errors.any?
  #error_explanation
    h2 = "#{pluralize(@point.errors.count, "error")} prohibited this point from being saved:"
    ul
      - @point.errors.full_messages.each do |message|
        li = message

.field
  = f.label :name
  = f.text_field :name

app/views/admin/points/edit.html.slim
h1 区間 - 編集

= form_for([:admin, @ekiden, @point], html: { class: 'ui form' })  do |f|
  .ui.stackable.grid
    .row
      .ten.wide.column
        = render 'form', f: f
    .row
      .five.wide.column
        = f.submit '保存', class: 'ui button primary'
      .five.wide.column
        = link_to '一覧へ', admin_ekiden_points_path(@ekiden), class: 'ui gray button'

app/views/admin/points/index.html.slim
h1 #{@ekiden.name} - チェックポイント

.ui.stackable.grid
  .five.wide.column
    = link_to '登録', new_admin_ekiden_point_path(@ekiden), class: 'ui button green'
  .five.wide.column
    = link_to '駅伝一覧へ', admin_ekidens_path(@ekiden), class: 'ui button'

table.ui.celled.small.table
  thead
    tr
      th ID
      th チェックポイント名
      th
      th

  tbody
    - @points.each do |point|
      tr
        td = point.id
        td = point.name
        td = link_to '編集', edit_admin_ekiden_point_path(@ekiden, point), class: 'ui green button'
        td = link_to '削除', admin_ekiden_point_path(@ekiden, point), data: { confirm: '本当に消します。よろしいですか1?' }, method: :delete, class: 'ui red button'

app/views/admin/points/new.html.slim
h1 区間 - 新規作成

= form_for([:admin, @ekiden, @point], html: { class: 'ui form' })  do |f|
  .ui.stackable.grid
    .row
      .ten.wide.column
        = render 'form', f: f
    .row
      .five.wide.column
        = f.submit '保存', class: 'ui button primary'
      .five.wide.column
        = link_to '一覧へ', admin_ekiden_points_path(@ekiden), class: 'ui gray button'