config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index", as: :root
  resources :tournaments, only: %i[index show]
  get "/ranking", to: "ranking#index", as: "ranking"
  get "/search", to: "search#index", as: "search"

  resources :athletes, only: %i[index show] do
    member do
      get "graph"
    end
  end

  namespace :admin do
    root to: "home#index", as: :root
    get "login", to: "sessions#new", as: :new_session
    post "login", to: "sessions#create", as: :session
    delete "logout", to: "sessions#destroy", as: :destroy_session

    resources :competitions
    resources :athletes
    resources :tournaments
    resources :short_results
    resources :long_results
    resources :field_results
    resources :relay_results
    resources :road_results
    resources :decathlon_results
    resources :ekidens do
      resources :raps do
        post :broadcast, to: "raps#broadcast"
      end
      resources :kukans
      resources :points
    end
  end

  get "/mentenance", to: "mentenance#index", as: "mentenance"
  root "errors#routing_error"
  get "*anything" => "errors#routing_error"
end

app/models/long_result.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: long_results
#
#  id               :bigint           not null, primary key
#  condition        :string
#  established_date :date
#  finish           :integer
#  grade            :string
#  group            :string
#  information      :string
#  official         :boolean
#  rane             :string
#  result           :bigint
#  round            :string
#  athlete_id       :integer
#  competition_id   :integer
#  tournament_id    :integer
#
class LongResult < ApplicationRecord
  belongs_to :athlete
  belongs_to :tournament
  belongs_to :competition

  before_save :set_grade

  private

  def set_grade
    self.grade = athlete.grade if grade.blank?
  end
end

app/controllers/admin/long_results_controller.rb
# frozen_string_literal: true

class Admin::LongResultsController < Admin::BaseController
  before_action :set_long_result, only: %i[edit update destroy]
  before_action :long_competition_options, only: %i[new edit create update edit destroy]

  def index
    @q = LongResult.ransack(params[:q])
    @q.sorts = "id desc" if @q.sorts.empty?
    @long_results = @q.result(distinct: true).page(params[:page])
  end

  def new
    @long_result = LongResult.new(official: true)
  end

  def edit
  end

  def create
    @long_result = LongResult.new(long_result_params)
    if @long_result.save
      flash[:notice] = "新規作成しました"
      redirect_to edit_admin_long_result_path(@long_result)
    else
      flash[:notice] = "新規作成に失敗しました"
      render :new
    end
  end

  def update
    if @long_result.update(long_result_params)
      flash[:notice] = "更新しました"
      redirect_to edit_admin_long_result_path(@long_result)
    else
      flash[:notice] = "更新に失敗しました"
      render :edit
    end
  end

  def destroy
    if @long_result.destroy
      flash[:notice] = "削除しました"
      redirect_to admin_long_results_path, notice: "削除しました"
    else
      flash[:notice] = "削除に失敗しました"
      redirect_to edit_admin_long_results_path(@long_result), error: "削除に失敗しました"
    end
  end

  private

    def set_long_result
      @long_result = LongResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def long_result_params
      params[:long_result][:result] = result_parse(params[:long_result][:result])
      params.require(:long_result).permit(
        :competition_id,
        :result,
        :round,
        :group,
        :rane,
        :finish,
        :athlete_id,
        :tournament_id,
        :grade,
        :established_date,
        :information,
        :condition,
        :official,
      )
    end

    def long_competition_options
      @competition_options =
        Competition.where(kind: :long).order(:position).each_with_object([]) do |competition, arr|
          arr << [competition.name, competition.id]
        end
    end
end

app/views/admin/long_results/_form.html.slim
.ui.stackable.grid

  - if @long_result.errors.any?
    .ui.segments
      .ui.segment.tertiary.inverted.red
        h2 エラー
      .ui.segment
        strong 以下の入力値を訂正してください。
        ul
        - @long_result.errors.full_messages.each do |message|
          li
            = message

  .six.wide.column
    .field
      = f.label :competition_id
      = f.select :competition_id, @competition_options, { include_blank: true }, class: 'ui dropdown'

  .six.wide.column
    .field
      = f.label :tournament_id
      = f.select :tournament_id, Tournament.order('id desc').pluck(:name, :id), { include_blank: true }, class: 'ui dropdown'

  .six.wide.column
    .field
      = f.label :athlete_id
      = f.select :athlete_id, Athlete.order('active desc').pluck(:name, :id), { include_blank: true }, class: 'ui dropdown'

  .six.wide.column
    .field
      = f.label :result
      = f.text_field :result, value: show_result(@long_result&.result), placeholder: '15.30.00'

  .six.wide.column

  .six.wide.column
    .field
      = f.label :round
      = f.text_field :round, placeholder: '決勝とか記録会とか'

  .six.wide.column
    .field
      = f.label :group
      = f.number_field :group

  .six.wide.column
    .field
      = f.label :rane
      = f.text_field :rane

  .six.wide.column
    .field
      = f.label :finish
      = f.number_field :finish

  .six.wide.column
    .field
      = f.label :established_date
      = f.date_field :established_date, value: @long_result.established_date.present? ? @long_result.established_date : Tournament.all.order('start_day DESC').first.start_day

  .six.wide.column
    .field
      = f.label :information
      = f.text_field :information, placeholder: 'PB, Q, q, 電通大記録...'

  .six.wide.column
    .field
      = f.label :condition
      = f.text_field :condition, placeholder: '豪雨, めっちゃ暑い'

  .six.wide.column
    .field
      .ui.checkbox
        = f.check_box :official, {}, "true", "false"
        = f.label :official

app/views/admin/long_results/edit.html.slim
h1 長距離結果 - 編集
= form_for([:admin, @long_result], html: { class: 'ui form' })  do |f|
  = render 'form', f: f

  .ui.stackable.grid
    .five.wide.column
      = f.submit '更新', class: 'ui button primary'
    .five.wide.column
      = link_to '長距離結果一覧へ', admin_long_results_path, class: 'ui gray button'
    - if @long_result.tournament_id.present?
      .five.wide.column
        = link_to '大会画面へ', admin_tournament_path(@long_result.tournament), class: 'ui gray button'

app/views/admin/long_results/index.html.slim
h1 長距離 結果一覧

= link_to '長距離 結果登録', new_admin_long_result_path, class: 'ui button green'

table.ui.celled.small.table
  thead
    tr
      th = sort_link(@q, :id, 'ID')
      th = sort_link(@q, :competition, '種目')
      th = sort_link(@q, :athlete_id, '選手')
      th = sort_link(@q, :result, '結果')
      th ラウンド
      th 組
      th レーン
      th 着順
      th 大会
      th = sort_link(@q, :established_date, '樹立日')
      th 情報
      th 環境
      th
      th

  tbody
    - @long_results.each do |long_result|
      tr
        td = long_result.id
        td = long_result.competition.name
        td
          - if long_result.grade.present?
            = I18n.t("enumerize.athlete.grade.#{long_result.grade}")
          = long_result&.athlete&.name
        td = show_result(long_result.result)
        td = long_result.round
        td = long_result.group
        td = long_result.rane
        td = long_result.finish
        td = long_result&.tournament&.name
        td = long_result.established_date
        td = long_result.information
        td = long_result.condition
        td = link_to '編集', edit_admin_long_result_path(long_result), class: 'ui green button'
        td = link_to '削除', admin_long_result_path(long_result), data: { confirm: '本当に消します。よろしいですか1?' }, method: :delete, class: 'ui red button'
= paginate @long_results

app/views/admin/long_results/new.html.slim
h1 長距離結果 - 新規登録
= form_for([:admin, @long_result], html: { class: 'ui form' })  do |f|
  = render 'form', f: f

  .ui.stackable.grid
    .six.wide.column
      = f.submit '登録', class: 'ui button primary'
    .six.wide.column
      = link_to '長距離結果一覧へ', admin_long_results_path, class: 'ui gray button'