config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index", as: :root
  resources :tournaments, only: %i[index show]
  get "/ranking", to: "ranking#index", as: "ranking"
  get "/search", to: "search#index", as: "search"

  resources :athletes, only: %i[index show] do
    member do
      get "graph"
    end
  end

  namespace :admin do
    root to: "home#index", as: :root
    get "login", to: "sessions#new", as: :new_session
    post "login", to: "sessions#create", as: :session
    delete "logout", to: "sessions#destroy", as: :destroy_session

    resources :competitions
    resources :athletes
    resources :tournaments
    resources :short_results
    resources :long_results
    resources :field_results
    resources :relay_results
    resources :road_results
    resources :decathlon_results
    resources :ekidens do
      resources :raps do
        post :broadcast, to: "raps#broadcast"
      end
      resources :kukans
      resources :points
    end
  end

  get "/mentenance", to: "mentenance#index", as: "mentenance"
  root "errors#routing_error"
  get "*anything" => "errors#routing_error"
end

app/models/rap.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: raps
#
#  id          :bigint           not null, primary key
#  athlete     :string
#  broadcasted :boolean          default(FALSE)
#  memo        :text
#  point       :string
#  rap_time    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  ekiden_id   :integer
#
class Rap < ApplicationRecord
  belongs_to :ekiden
end

app/controllers/admin/raps_controller.rb
# frozen_string_literal: true

class Admin::RapsController < Admin::BaseController
  before_action :set_ekiden
  before_action :set_rap, only: %i[edit update destroy broadcast]
  before_action :set_options, only: %i[edit new create update]

  def index
    @raps = Rap.where(ekiden_id: @ekiden.id).order("created_at asc")
  end

  def new
    @rap = Rap.new
  end

  def edit
    @time_sum = Rap.where(ekiden_id: @ekiden.id, athlete: @rap.athlete).sum(:rap_time)
  end

  def create
    @rap = Rap.new(rap_params.merge(ekiden_id: @ekiden.id))
    @rap.rap_time = get_rap_time
    if @rap.save
      flash[:notice] = "新規作成しました"
      redirect_to edit_admin_ekiden_rap_path(@ekiden, @rap)
    else
      flash[:notice] = "新規作成に失敗しました"
      render :new
    end
  end

  def update
    if @rap.update(rap_params)
      flash[:notice] = "更新しました"
      redirect_to edit_admin_ekiden_rap_path(@ekiden, @rap)
    else
      flash[:notice] = "更新に失敗しました"
      render :edit
    end
  end

  def destroy
    flash[:notice] = if @rap.destroy
                       "削除しました"
                     else
                       "削除に失敗しました"
                     end
    redirect_to admin_ekiden_raps_path(@ekiden)
  end

  def broadcast
    if @rap.update(broadcasted: true)
      # Slack::Notifier.new(Settings.webhook_url, username: '駅伝速報', icon_emoji: ':obama:').ping(params[:broadcast_message])
      Slack::Notifier.new("https://hooks.slack.com/services/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",
                          username: "駅伝速報", icon_emoji: ":obama:").ping(params[:broadcast_message])
      flash[:notice] = "配信しました"
      redirect_to admin_ekiden_raps_path(@ekiden, @rap)
    else
      flash[:notice] = "更新に失敗しました"
      render :edit
    end
  end

  private

    def set_ekiden
      @ekiden = Ekiden.find(params[:ekiden_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_rap
      @rap = if params[:id].nil?
               Rap.find(params[:rap_id])
             else
               Rap.find(params[:id])
             end
    end

    def set_options
      @point_options = @ekiden.points.order("id").pluck(:name, :name)
      @athlete_options = athlete_options
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rap_params
      params.require(:rap).permit(:point, :athlete, :memo)
    end

    # integer[ms]
    def get_rap_time
      last_rap = Rap.where(ekiden_id: @ekiden.id).order("created_at").last
      p Time.zone.now
      p @ekiden.start_at
      if last_rap.nil?
        # time_distance_milli_second(Time.zone.now, @ekiden.start_at)
        nil
      else
        time_distance_milli_second(Time.zone.now, last_rap.created_at)
      end
    end

    def time_distance_milli_second(a, b)
      ((a - b) * 1000).to_i
    end

    def athlete_options
      options = ["わからん"]
      @ekiden.kukans.order("kukan_number").each { |kukan| options << ["#{kukan.kukan_number}区 #{kukan.athlete}"] }
      options
    end
end

app/views/admin/raps/_form.html.slim
- if @rap.errors.any?
  #error_explanation
    h2 = "#{pluralize(@rap.errors.count, "error")} prohibited this rap from being saved:"
    ul
      - @rap.errors.full_messages.each do |message|
        li = message

.field
  = f.label :point
  = f.select :point, @point_options, {}, class: 'ui dropdown'

.field
  = f.label :athlete
  = f.select :athlete, @athlete_options, {}, class: 'ui dropdown'

app/views/admin/raps/edit.html.slim
h1 ラップ - 編集 or 配信

.ui.stackable.segment
  .ui.form
    = form_tag admin_ekiden_rap_broadcast_path(@ekiden, @rap), method: :post do
      = label_tag '配信文章'
      .field
        = text_area_tag :broadcast_message, "-----------------------------------------\n地点：#{@rap.point}" + "\n選手：#{@rap.athlete}" + "\n通過時刻：#{@rap.created_at.strftime("%H:%M:%S")}" + "\nタイム：#{show_result(@time_sum)}" + "\n前回ポイントからのラップ：#{show_result(@rap.rap_time)}"
      .field
        =  submit_tag' slackに配信する', class: 'ui button green'
        - if @rap.broadcasted
          p.ui.header.red ※配信済みです 

= form_for([:admin, @ekiden, @rap], html: { class: 'ui form' })  do |f|
  .ui.stackable.grid
    .row
      .ten.wide.column
        = render 'form', f: f
    .row
      .five.wide.column
        = f.submit '保存', class: 'ui button primary'
      .five.wide.column
        = link_to '一覧へ', admin_ekiden_raps_path(@ekiden), class: 'ui gray button'

app/views/admin/raps/index.html.slim
h1 #{@ekiden.name} - これまでのラップ - スタート：#{l @ekiden.start_at}

.ui.stackable.grid
  .five.wide.column
    = link_to '登録', new_admin_ekiden_rap_path(@ekiden), class: 'ui button green'
  .five.wide.column
    = link_to '駅伝一覧へ', admin_ekidens_path(@ekiden), class: 'ui button'

table.ui.celled.small.table
  thead
    tr
      th 通過地点
      th 選手
      th ラップタイム(前回のチェックポイントから)
      th 通過タイム
      th 配信済?
      th
      th

  tbody
    - @raps.each do |rap|
      tr
        td = rap.point
        td = rap.athlete
        td = show_result(rap.rap_time)
        td = l rap.created_at
        td 
          - if rap.broadcasted
            | ✓
        td = link_to '編集 & 発信', edit_admin_ekiden_rap_path(@ekiden, rap), class: 'ui green button'
        td = link_to '削除', admin_ekiden_rap_path(@ekiden, rap), data: { confirm: '本当に消します。よろしいですか1?' }, method: :delete, class: 'ui red button'

app/views/admin/raps/new.html.slim
h1 ラップ - 作成

= form_for([:admin, @ekiden, @rap], html: { class: 'ui form' })  do |f|
  .ui.stackable.grid
    .row
      .ten.wide.column
        = render 'form', f: f
    .row
      .five.wide.column
        = f.submit 'ラップをとる！！！', class: 'ui huge button red'
      .five.wide.column
        = link_to '一覧へ', admin_ekiden_raps_path(@ekiden), class: 'ui gray button'